-- Make the DDL compatible with both MariaDB and H2 (used in tests).
-- Avoid MariaDB-specific clauses like UNSIGNED, ENGINE, CHARSET and ON UPDATE.
CREATE TABLE todos (
  id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  text VARCHAR(255) NOT NULL,
  completed BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);
